export const RELIGION_OPTIONS = [
  "None",
  "Agnostic",
  "Atheist",
  "Spiritual but not religious",
  "Humanist",
  "Secular",
  "Deist",
  "Theist",
  "Monotheist",
  "Polytheist",
  "Pantheist",
  "Panentheist",
  "Animist",
  "Shamanist",
  "New Age",
  "Christian",
  "Catholic",
  "Roman Catholic",
  "Eastern Orthodox",
  "Oriental Orthodox",
  "Protestant",
  "Anglican",
  "Episcopalian",
  "Baptist",
  "Methodist",
  "Lutheran",
  "Presbyterian",
  "Reformed",
  "Pentecostal",
  "Charismatic",
  "Evangelical",
  "Seventh-day Adventist",
  "Latter-day Saints",
  "Jehovah's Witness",
  "Quaker",
  "Unitarian Universalist",
  "Mennonite",
  "Amish",
  "Church of Christ",
  "Christian Science",
  "Eastern Catholic",
  "Coptic Christian",
  "Assyrian Church of the East",
  "Nestorian",
  "Gnostic",
  "Islam",
  "Sunni",
  "Shia",
  "Sufi",
  "Ibadi",
  "Ahmadiyya",
  "Ismaili",
  "Zaydi",
  "Quranist",
  "Judaism",
  "Orthodox Judaism",
  "Conservative Judaism",
  "Reform Judaism",
  "Reconstructionist Judaism",
  "Hasidic",
  "Karaite Judaism",
  "Hinduism",
  "Vaishnavism",
  "Shaivism",
  "Shaktism",
  "Smartism",
  "Buddhism",
  "Theravada",
  "Mahayana",
  "Vajrayana",
  "Zen",
  "Nichiren",
  "Pure Land",
  "Jainism",
  "Sikhism",
  "Taoism",
  "Confucianism",
  "Shinto",
  "Baha'i",
  "Zoroastrianism",
  "Yazidism",
  "Druze",
  "Rastafari",
  "Pagan",
  "Neopagan",
  "Wicca",
  "Druidry",
  "Heathenry",
  "Asatru",
  "Hellenism",
  "Kemetic",
  "Roman Polytheism",
  "Celtic Polytheism",
  "Slavic Native Faith",
  "Baltic Native Faith",
  "African Traditional Religion",
  "Yoruba",
  "Vodun",
  "Ifa",
  "Santeria",
  "Candomble",
  "Umbanda",
  "Native American Spirituality",
  "Inuit Traditional",
  "Maori Spirituality",
  "Aboriginal Australian Spirituality",
  "Sami Shamanism",
  "Chinese Folk Religion",
  "Korean Shamanism",
  "Japanese Folk Religion",
  "Southeast Asian Folk Religion",
  "Tenrikyo",
  "Shugendo",
  "Eckankar",
  "Scientology",
  "Unification Church",
  "Caodaism",
  "Falun Gong",
  "Samaritanism",
  "Brahma Kumaris",
  "Radhasoami",
  "Swedenborgian",
  "Theosophy",
  "Anthroposophy",
  "Raelism",
  "Tengrism",
  "Manichaeism",
  "Mandaeism",
  "Satanism",
  "LaVeyan Satanism",
  "Church of Satan",
  "Temple of Set",
  "Pastafarianism",
  "Assemblies of God",
  "Church of God",
  "Foursquare",
  "Calvinism",
  "Church of the Nazarene",
  "Moravian Church",
  "Salvation Army",
  "Greek Orthodox",
  "Russian Orthodox",
  "Serbian Orthodox",
  "Antiochian Orthodox",
  "Armenian Apostolic",
  "Ethiopian Orthodox",
  "Eritrean Orthodox",
  "Syriac Orthodox",
  "Maronite",
  "Syriac Catholic",
  "Chaldean Catholic",
  "Melkite Catholic",
  "Greek Catholic",
  "Ukrainian Catholic",
  "Polish National Catholic",
  "Liberal Quaker",
  "Conservative Quaker",
  "Independent Catholic",
  "Non-denominational Christian",
  "Messianic Judaism",
  "Yeshivish",
  "Hasidic Chabad",
  "Reform Hindu",
  "Soka Gakkai",
  "Tiantai",
  "Huayan",
  "Madhyamaka",
  "Yogacara",
  "Nichiren Shoshu",
  "Bon",
  "Bektashi",
  "Alevi",
  "Dharma",
  "Unspecified",
];
